const $ = id => document.getElementById(id);
const defaults = {birth:"1991-05-19",targetAge:85,sleepHours:8,routineHours:3,goldEnd:35,silverEnd:50,bronzeEnd:65};
let cfg = {...defaults, ...JSON.parse(localStorage.getItem("lifeConfigV4") || "{}")};
function fmtInt(n){return Math.max(0, Math.floor(n)).toLocaleString("vi-VN");}
function fmt1(n){return Math.max(0, n).toFixed(1).replace(".", ",");}
function addYears(date, years){const d=new Date(date); d.setFullYear(d.getFullYear()+years); return d;}
function addMonths(date, months){const d=new Date(date); d.setMonth(d.getMonth()+months); return d;}
function diffParts(start,end){if(end<=start) return {years:0,months:0,days:0,hours:0,minutes:0}; let years=end.getFullYear()-start.getFullYear(); let yTry=addYears(start, years); if(yTry>end){years--; yTry=addYears(start, years);} let months=(end.getFullYear()-yTry.getFullYear())*12 + (end.getMonth()-yTry.getMonth()); let mTry=addMonths(yTry, months); if(mTry>end){months--; mTry=addMonths(yTry, months);} const totalMinutes=Math.floor((end-mTry)/60000); const days=Math.floor(totalMinutes/1440); const hours=Math.floor((totalMinutes-days*1440)/60); const minutes=totalMinutes - days*1440 - hours*60; return {years,months,days,hours,minutes};}
function ageYears(birth,now){return (now-birth)/(365.2425*86400000);}
function yearsToAge(birth,now,age){const target=addYears(birth, age); return Math.max(0, (target-now)/(365.2425*86400000));}
function shortSpan(years){if(years<=0.02) return "Hết"; if(years<1) return fmtInt(years*12)+" tháng"; return fmt1(years)+" năm";}
function stageName(age){if(age<cfg.goldEnd) return "VÀNG"; if(age<cfg.silverEnd) return "BẠC"; if(age<cfg.bronzeEnd) return "ĐỒNG"; if(age<cfg.targetAge) return "GỖ"; return "HẾT";}
function stageCopy(stage){if(stage==="VÀNG") return "Bạn đang ở vùng năng lượng mạnh nhất của cuộc đời."; if(stage==="BẠC") return "Bạn vẫn còn ở vùng sung mãn, nhưng quỹ này không kéo dài mãi."; if(stage==="ĐỒNG") return "Phần đời còn dài, nhưng tuổi đẹp nhất đã thu hẹp đáng kể."; if(stage==="GỖ") return "Giờ là lúc ưu tiên điều đáng sống nhất trong thời gian còn lại."; return "Quỹ tuổi mục tiêu đã khép lại.";}
function validate(next){if(!next.birth) return "Hãy nhập ngày sinh."; if(next.targetAge<=1 || next.targetAge>130) return "Tuổi dự kiến chưa hợp lệ."; if(next.sleepHours<0 || next.routineHours<0 || next.sleepHours+next.routineHours>=24) return "Ngủ + sinh hoạt phải nhỏ hơn 24 giờ/ngày."; if(!(0<next.goldEnd && next.goldEnd<next.silverEnd && next.silverEnd<next.bronzeEnd && next.bronzeEnd<next.targetAge)) return "Mốc phải tăng dần: Vàng < Bạc < Đồng < Tuổi dự kiến."; return "";}
function setInputs(){["birth","targetAge","sleepHours","routineHours","goldEnd","silverEnd","bronzeEnd"].forEach(id=>$(id).value=cfg[id]);}
function setTimeline(){const total=cfg.targetAge; $("segGold").style.width=(cfg.goldEnd/total*100)+"%"; $("segSilver").style.width=((cfg.silverEnd-cfg.goldEnd)/total*100)+"%"; $("segBronze").style.width=((cfg.bronzeEnd-cfg.silverEnd)/total*100)+"%"; $("segWood").style.width=((cfg.targetAge-cfg.bronzeEnd)/total*100)+"%";}
function update(){const now=new Date(); const birth=new Date(cfg.birth+"T00:00:00"); const end=addYears(birth, Number(cfg.targetAge)); const remSec=Math.max(0,(end-now)/1000); const remYears=remSec/(365.2425*86400), remMonths=remSec/((365.2425/12)*86400), remWeeks=remSec/604800, remDays=remSec/86400, remHours=remSec/3600, remMinutes=remSec/60; const parts=diffParts(now,end); const sleep=Number(cfg.sleepHours), routine=Number(cfg.routineHours), freeHours=Math.max(0,24-sleep-routine), freeRatio=freeHours/24; const usableYears=remYears*freeRatio, usableMonths=usableYears*12, usableWeeks=usableYears*365.2425/7; $("usableMonths").textContent=fmtInt(usableMonths); $("usableWeeks").textContent=fmtInt(usableWeeks); $("heroCopy").textContent=`Bạn không còn nhiều thời gian như bạn vẫn nghĩ. Điều đáng sợ không phải là thời gian ít đi, mà là ta thường chỉ nhận ra điều đó quá muộn.`; const tomorrow=new Date(now); tomorrow.setHours(24,0,0,0); const remainTodaySec=Math.max(0,Math.floor((tomorrow-now)/1000)); const hh=String(Math.floor(remainTodaySec/3600)).padStart(2,'0'); const mm=String(Math.floor((remainTodaySec%3600)/60)).padStart(2,'0'); const ss=String(remainTodaySec%60).padStart(2,'0'); $("todayClock").textContent=`${hh}:${mm}:${ss}`; const passed=(now.getHours()*3600 + now.getMinutes()*60 + now.getSeconds())/86400; $("dayFill").style.width=(passed*100)+"%"; $("dayPassed").textContent=`Đã qua ${(passed*100).toFixed(1)}%`; $("dayRemain").textContent=`Còn ${((1-passed)*100).toFixed(1)}%`; $("lifeRemainMain").textContent=`${parts.years} năm ${parts.months} tháng`; $("lifeRemainSub").textContent=`Tương đương ${fmtInt(remDays)} ngày • ${fmtInt(remWeeks)} tuần`;    const age=Math.max(0, ageYears(birth, now)); const stage=stageName(age); $("currentStage").textContent=stage; $("timelineCopy").textContent=stageCopy(stage); $("tickGold").textContent=cfg.goldEnd; $("tickSilver").textContent=cfg.silverEnd; $("tickBronze").textContent=cfg.bronzeEnd; $("tickTarget").textContent=cfg.targetAge; const lifePct=Math.max(0,Math.min(100, age/cfg.targetAge*100)); $("lifeMarker").style.left=lifePct+"%"; $("todayDate").textContent=new Intl.DateTimeFormat('vi-VN',{day:'2-digit',month:'2-digit',year:'numeric'}).format(now); $("todayWeekday").textContent=new Intl.DateTimeFormat('vi-VN',{weekday:'long'}).format(now); setTimeline();}
function openDrawer(on){$("drawer").classList.toggle("open", on); $("mask").classList.toggle("show", on);} $("drawerOpen").onclick=()=>openDrawer(true); $("drawerClose").onclick=()=>openDrawer(false); $("mask").onclick=()=>openDrawer(false); $("saveBtn").onclick=()=>{const next={birth:$("birth").value,targetAge:Number($("targetAge").value),sleepHours:Number($("sleepHours").value),routineHours:Number($("routineHours").value),goldEnd:Number($("goldEnd").value),silverEnd:Number($("silverEnd").value),bronzeEnd:Number($("bronzeEnd").value)}; const err=validate(next); if(err){alert(err); return;} cfg=next; localStorage.setItem("lifeConfigV4", JSON.stringify(cfg)); openDrawer(false); update();}; setInputs(); update(); setInterval(update, 1000);
